services:
  build:
    image: ${PREBUILD_HUB}/${IMAGE_NAMESPACE}/build-${STAGE}:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ${PREBUILD_HUB}/${IMAGE_NAMESPACE}/build-${STAGE}:latest
    volumes:
      - ./../../:/source
      - /home
    user: 1000:1000
    environment:
      HOME: /home
    network_mode: bridge
