services:
  laporan-uat:
    image: ${HUB}/${IMAGE_NAMESPACE}/laporan-uat-devel:${VERSION:-latest}
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      update_config:
        parallelism: 1
        delay: 0s
        order: start-first
      labels:
        - "caddy=laporan-uat.dev.siap.id"
        - "caddy.tls=/tls/star.dev.siap.id.crt /tls/star.dev.siap.id.key"
        - "caddy.reverse_proxy={{upstreams 80}}"
    networks:
      - global-net

  clockwork-clean:
    image: ${HUB}/${IMAGE_NAMESPACE}/laporan-uat-devel:${VERSION:-latest}
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=CRON_TZ=Asia/Jakarta 0 0 0 * * *"
        - "swarm.cronjob.skip-running=true"
      replicas: 0
      restart_policy:
        condition: none
    command:
      php artisan clockwork:clean --expiration=604800

networks:
  global-net:
    external: true
